service: simpleNode
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
            # every day at 11:40 PM
            - schedule: cron(40 23 * * ? *)
